# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

[things]
[things.limits]
create = 10
update = 10

[users]
[users.limits]
create = 10
update = 10

[auth]
[auth.limits]
create = 10
update = 10

[channels]
[channels.limits]
create = 10
update = 10

[groups]
[groups.limits]
create = 10
update = 10
